name              "virtualbox"
maintainer        "Phil Cohen"
maintainer_email  "github@phlippers.net"
license           "MIT"
description       "Install Virtualbox and Guest Additions"
version           "0.2.0"
supports          "ubuntu"
recipe            "default", "Install Virtualbox and Guest Additions"

depends "apt"
